service: serverlesstest
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs18.x
  region: eu-west-2
  memorySize: 128
plugins:
  - serverless-offline
  - serverless-webpack
custom:
  webpack:
    webpackConfig: ./webpack.config.js
    excludeFiles: '**/*.test.js'
    excludeRegex: \.ts|test|\.map
functions:
  function1:
    handler: index.handler
    events:
      - http:
          path: /
          method: get
          cors: true

