name: CI

on:
  pull_request:
    branches:
      - '*'
#  push:
#    branches-ignore:
#      - staging
#      - production

jobs:
  serverless-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18'
    - name: Install Serverless Framework
      run: npm install -g serverless
    - name: Cache yarn dependencies
      uses: actions/cache@v2
      id: yarn-cache
      with:
        path: |
          ${{ steps.yarn-cache-dir-path.outputs.dir }}
          **/node_modules
        key: our-cache-yarn-${{ hashFiles('**/yarn.lock.json') }}
    - name: Install packages
      if: steps.yarn-cache.outputs.cache-hit != 'true'
      run: yarn
    - name: Echo GITHUB_PR_NUMBER
      env:
        GITHUB_PR_NUMBER: ${{github.event.pull_request.number}}
      run: echo "$GITHUB_PR_NUMBER"
    - name: Deploy to Serverless
      run: serverless deploy --stage ${{github.event.pull_request.number}}

  remove-deployment:
    if: github.event_name == 'pull_request' && github.ref != 'refs/heads/staging' && github.ref != 'refs/heads/production'
    runs-on: ubuntu-latest
    steps:
    - name: Install Serverless Framework
      run: npm install -g serverless
    - name: Remove deployment from Serverless
      run: serverless remove --stage $GITHUB_REF_NAME
      # - name: serverless deploy
      # - uses: serverless/github-action@v3.2
      #  with:
      #    args: deploy
      #  env:
          # or if using AWS credentials directly
          # AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          # AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      # - run: npm ci
        #uses: borales/actions-yarn@v4
        #with:
        #  cmd: install # will run `yarn install` command
      #- name: serverless deploy
      #  uses: serverless/github-action@v3.2
      #  with:
      #    args: deploy
      #  env:
      #    SERVERLESS_ACCESS_KEY: ${{ secrets.SERVERLESS_ACCESS_KEY }}
        # or if using AWS credentials directly
        # AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        # AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
#    steps:
#      - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
#      - run: echo "🐧 This job is now running on a ${{ runner.os }} server hosted by GitHub!"
#      - run: echo "🔎 The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
#      - name: Check out repository code
#        uses: actions/checkout@v3
#      - run: echo "💡 The ${{ github.repository }} repository has been cloned to the runner."
#      - run: echo "🖥️ The workflow is now ready to test your code on the runner."
#      - name: List files in the repository
#        run: |
#          ls ${{ github.workspace }}
#      - run: echo "🍏 This job's status is ${{ job.status }}."
