name: Serverless Delete

# only trigger on pull request closed events
on:
  pull_request:
    types: [closed]

jobs:
  merge-job:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
    - name: Echo PR number
      run: echo "PR ${{ github.event.pull_request.number }} has been merged"
    - name: Echo branch name
      run: echo "${{ github.ref_name }}"

  close-job:
    if: github.event.pull_request.merged == false
    runs-on: ubuntu-latest
    steps:
    - name: Echo PR number
      run: echo "PR ${{ github.event.pull_request.number }} has been closed without being merged"
    - name: Echo branch name
      run: echo "${{ github.ref_name }}"

      
    #  - name: Set Branch name
    #    run: |
    #      BRANCH=$(cat ${{ github.event_path }} | jq --raw-output '.ref')
    #      echo "${{ github.repository }} has ${BRANCH} branch"
    #      echo "::set-env name=STAGE::$(echo ${BRANCH})"
    #  - name: Echo Branch name
    #    run: echo Deleting from STAGE:$STAGE

      # Install npm and it's dependencies
    #  - name: npm install dependencies
    #    run: npm install

      # sls remove
    #  - name: Serverless
    #    uses: serverless/github-action@v1.53.0
    #    with:
    #      args: remove